### PR TITLE
[Feature] Select grid from clue list

### LINKED ISSUE #22: Selecting a clue in the list locks the selection, and highlights the clue on the grid, and vice versa.
## Requirements (all devices and screen sizes)

- [x] When the user selects a clue in the clue list, on the grid, or the single clue under the grid, it locks the selection and highlights the clue in all three places the clue appears
- [x] Selecting an already selected clue (from the clue list or single clue under the grid) toggles it, and the highlighting disappears
- [x] Selecting a different clue from the one currently selected changes the highlights to the newly selected clue

## Requirements (In desktop (but not smartphone) view)
- [x] When no clue has been selected, and when the mouse moves over clues in the clue list, the clue under the mouse is temporarily highlighted on the grid (as per current functionality).
- [x] Disable hover when clue is selected by click

### PR DESCRIPTION
**Pull request by Lily2point0**
- implement clue toggle
- block hover on clue clicked
- reset hover on toggle off

Fixes #22

### CODE REVIEW

**Comment by railsagainstignorance** [comment]
clicktastic. Excellent.
One suggestion: make the clue highlighting more obvious (not easy to see that clicking on the grid has also selected+locked a clue in the clue list.

**Comment by Lily2point0** [comment]
Highlighted clues are now 'claret-1'.

**Comment by railsagainstignorance** [comment]
nice.
Noticed a quirk: 
- when a clue is selected in the clue list, it locks and stays locked even after mouseover on the clue list and the grid.
- but, when a clue is selected via the grid, it locks and stays locked during mouseover on the grid but unlocks during mouseover of the clue list.

**Comment by railsagainstignorance** [comment]
excellent.
new quirk: when I select/lock a clue in the clue list from the Down section, i.e. where the screen is scrolled up a bit, the screen jumps back down to show that selected clue in the grid, and I lose my place in the clue list.

**Pull request merged**
